FROM php:7.2-fpm-alpine

# Update Timezone
RUN apk add --update tzdata && \
    cp /usr/share/zoneinfo/Asia/Bangkok /etc/localtime && \
    apk del tzdata

# Install Additional dependencies
RUN apk update && apk add --no-cache \
    build-base shadow vim curl \
    openssh \
    git \
    npm \
    php7 \
    php7-fpm \
    php7-common \
    php7-pdo \
    php7-pdo_mysql \
    php7-mysqli \
    php7-mcrypt \
    php7-mbstring \
    php7-xml \
    php7-openssl \
    php7-json \
    php7-phar \
    php7-zip \
    php7-gd \
    php7-dom \
    php7-session \
    php7-zlib

# Add and Enable PHP-PDO Extenstions
RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-enable pdo_mysql
    
COPY ./config/php/php.ini /usr/local/etc/php/conf.d/php.ini
COPY ./web/ /var/www/web
WORKDIR /var/www/web

EXPOSE 9000