FROM nginx:1-alpine

# Update Timezone
RUN apk add --update tzdata && \
    cp /usr/share/zoneinfo/Asia/Bangkok /etc/localtime && \
    apk del tzdata


COPY ./config/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./web/ /var/www/web
WORKDIR /var/www/web

EXPOSE 80