version: '2'
services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    working_dir: /var/www/web
    volumes: 
      - ./web/:/var/www/web
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links: 
      - phpfpm
    ports:
      - 8080:80
  phpfpm:
    build: 
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./web/:/var/www/web
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=gZ83HQhJioNvJcV
      - MYSQL_PASSWORD=Mnp39cFy4X9RKNkNgPJCDF93A
      - MYSQL_ROOT_PASSWORD=69UgkZJsvooCUQfPTeDJx9EkiMnp39cFy4X9RKNkNgPJCDF93A
  phpmyadmin:
    image: nazarpc/phpmyadmin
    environment:
      - UPLOAD_SIZE=2G
      - SESSION_TIMEOUT=86400
    links:
      - mysql:mysql
    ports:
      - 5678:80
volumes:
  mysql-data:
    driver: local